name: Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Jalankan setiap hari
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Langkah untuk membersihkan cache (opsional, untuk menghindari konflik cache)
      - name: Clear GitHub Actions Cache
        run: |
          echo "Clearing cache..."
          rm -rf ${{ runner.temp }}/_github_home
          rm -rf ${{ runner.temp }}/_github_work

      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate GitHub Metrics
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: botsaga1 # Ganti dengan nama pengguna GitHub Anda
